/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The running build version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process and database liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured accounts */
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename an account or choose its icon */
        patch: operations["updateAccountProfile"];
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inbox summaries, newest first
         * @description `folder` picks the folder view by role and defaults to the inbox; the Trash view is where the reader's Empty Trash control lives. An unknown role is a 400, never an empty page.
         */
        get: operations["listInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One message with its sanitized body */
        get: operations["getMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The header alone, for a failed body */
        get: operations["getMessageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Reading feed and its digest */
        get: operations["listReading"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hybrid keyword plus meaning search */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Ivy a question about the selected accounts */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User tags and placed tags */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Correspondents derived from the mirror */
        get: operations["listPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One correspondent */
        get: operations["getPerson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rules as plain sentences */
        get: operations["listRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One rule */
        get: operations["getRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Smart checks */
        get: operations["listChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One smart check */
        get: operations["getCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mirror/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-account sync state and index health */
        get: operations["getMirrorHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mirror/messages/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make one hidden message visible again
         * @description A local mirror change, never an IMAP write. It only clears the disabled flag; a message the server still does not hold is hidden again by the next completed pass.
         */
        post: operations["restoreMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mirror/accounts/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make an account's removed mail visible again
         * @description The one-click answer to a mass-disable alert. It restores mail the server dropped. Rows that moved to another folder stay hidden (their mail is live there, so restoring them would show it twice), and rows a pass has not classified yet are left for the next completed pass to settle.
         */
        post: operations["restoreAccountHidden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mirror/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Permanently erase one hidden message
         * @description The only erasure Ivy has. It deletes the row and its attachments, unlinks the spool file, and erases the message's blob from the local store and every backup target when no other hidden message shares those bytes. An offline backup target keeps the deletion pending and the daily backup retries it. A live message is refused, so the reader's ordinary delete can never reach it.
         */
        delete: operations["purgeMessage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent hints that something changed
         * @description A stream of small typed hints that say what to refetch (round 37). Each frame is `event: <type>` and one `data:` line holding an Event as JSON. There are no event ids and no replay: after any reconnect, refetch what you are showing. A slow client's queue is bounded and drops its oldest hints. Comment lines (`: keepalive`) are heartbeats, and the first frame is `retry: 3000`. At most 16 streams are open at once.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live and recent outbox ops */
        get: operations["listOutbox"];
        put?: never;
        /**
         * Apply a reader action through the outbox
         * @description The one write path to IMAP. The op row is committed before the action is reported accepted; the IMAP command follows, and the mirror follows that. A move or delete needs an explicit confirmation from the UI before this call; an undo is the inverse action, enqueued the same way. A repeat of a live action returns the existing op instead of queueing a second one.
         */
        post: operations["enqueueOutbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Dismiss a terminal op
         * @description Removes a terminal row from the history. A live op is refused; it is never silently dropped.
         */
        delete: operations["dismissOutbox"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a failed op now
         * @description Returns a failed op to the queue immediately, clearing its attempt count so the retry cap is measured afresh.
         */
        post: operations["retryOutbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable code the UI maps to its own copy */
            code: string;
            message: string;
            detail?: string;
        };
        /** @description One hint on the event stream. It says what changed, never the new value. */
        Event: {
            /** @enum {string} */
            type: "message.changed" | "folder.changed" | "sync.state" | "outbox.state" | "health.alert";
            accountId?: string;
            folder?: string;
            /** @description Stable reason, used by health.alert */
            code?: string;
        };
        Version: {
            version: string;
        };
        Liveness: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            version: string;
            databases: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        TagColor: "sky" | "rose" | "teal" | "coral" | "lilac" | "mint" | "gold" | "sand" | "orchid" | "fern" | "slate" | "berry";
        /** @enum {integer} */
        AccountSlot: 1 | 2 | 3 | 4 | 5;
        /** @enum {string} */
        SyncState: "ok" | "syncing" | "auth-failed" | "unreachable";
        Account: {
            id: string;
            address: string;
            short: string;
            initial: string;
            /** @description The account's display name, empty when it has none */
            name: string;
            /** @description A chosen emoji or glyph, empty when it has none */
            icon: string;
            /** @description Whether GET /accounts/{id}/photo serves a photo */
            photo: boolean;
            slot: components["schemas"]["AccountSlot"];
            unread: number;
            smart: boolean;
            sync: components["schemas"]["SyncState"];
            /** @description What the sync is doing, as a short phrase with no time in it ("Up to date", "Reading your mailbox, newest first"). The browser appends "synced 4 min ago" from syncedAt. */
            syncNote: string;
            /**
             * Format: date-time
             * @description When the account's mailbox last synced, RFC 3339 in UTC. Absent until the first folder has synced.
             */
            syncedAt?: string;
            progress?: number;
            hidden?: components["schemas"]["HiddenMail"];
        };
        /** @description A partial rename; omitted fields keep their current value */
        AccountProfile: {
            displayName?: string;
            icon?: string;
        };
        Attachment: {
            id: string;
            name: string;
            size: string;
            /** @enum {string} */
            kind: "image" | "file";
            /** @enum {string} */
            tone?: "a" | "b";
            failed?: boolean;
        };
        MailSummary: {
            id: string;
            accountId: string;
            from: string;
            initials: string;
            /**
             * Format: date-time
             * @description The message's instant, RFC 3339 in UTC. The browser formats it in the viewer's own zone and locale; a message with no Date header carries the zero instant (0001-01-01T00:00:00Z) and shows no time.
             */
            date: string;
            subject: string;
            preview: string;
            unread: boolean;
            /** @description Whether the message carries the \\Flagged keyword */
            flagged?: boolean;
            needs: boolean;
            tag?: string;
        };
        MailMessage: {
            id: string;
            accountId: string;
            from: string;
            initials: string;
            /**
             * Format: date-time
             * @description The message's instant, RFC 3339 in UTC (see MailSummary).
             */
            date: string;
            subject: string;
            preview: string;
            unread: boolean;
            /** @description Whether the message carries the \\Flagged keyword */
            flagged?: boolean;
            needs: boolean;
            tag?: string;
            toShort: string;
            toFull: string;
            summary?: string;
            /** @description Server-sanitised HTML body, safe to place in the reader's sandboxed frame. Empty for a message with no HTML part; use paragraphs then. */
            html?: string;
            paragraphs: string[];
            attachments: components["schemas"]["Attachment"][];
        };
        Inbox: {
            items: components["schemas"]["MailSummary"][];
            needCount: number;
            unreadCount: number;
            readingWaiting: number;
            nextCursor?: string;
        };
        Issue: {
            id: string;
            sender: string;
            initials: string;
            minutes?: number;
            read: boolean;
            title: string;
            blurb?: string;
        };
        ReadingFeed: {
            digest: string;
            issues: components["schemas"]["Issue"][];
        };
        SearchHit: {
            id: string;
            accountId: string;
            from: string;
            /**
             * Format: date-time
             * @description The message's instant, RFC 3339 in UTC (see MailSummary).
             */
            date: string;
            subject: string;
            preview: string;
            hasAttachment?: boolean;
            tag?: string;
            semantic?: boolean;
        };
        SearchResults: {
            query: string;
            total: number;
            hits: components["schemas"]["SearchHit"][];
            nextCursor?: string;
        };
        AskRequest: {
            question: string;
            accountIds?: string[];
        };
        AskStep: {
            /** @enum {string} */
            kind: "search" | "read" | "think";
            text: string;
        };
        AskSource: {
            n: number;
            subject: string;
            meta: string;
        };
        AskAnswer: {
            question: string;
            steps: components["schemas"]["AskStep"][];
            answer: string[];
            sources: components["schemas"]["AskSource"][];
        };
        UserTag: {
            id: string;
            name: string;
            color: components["schemas"]["TagColor"];
            count: number;
        };
        PlacedTag: {
            id: string;
            name: string;
            count: number;
        };
        TagsOverview: {
            mine: components["schemas"]["UserTag"][];
            placed: components["schemas"]["PlacedTag"][];
            activeRules: number;
        };
        Conversation: {
            id: string;
            subject: string;
            preview: string;
            when: string;
            unread?: boolean;
        };
        Person: {
            id: string;
            name: string;
            initials: string;
            email: string;
            slot: components["schemas"]["AccountSlot"];
            latest: string;
            when: string;
            writesTo: string;
            since: string;
            tags: string[];
            conversations: components["schemas"]["Conversation"][];
        };
        Rule: {
            id: string;
            when: string;
            whenToken?: string;
            whenTail?: string;
            then: string;
            thenToken: string;
            thenColor?: components["schemas"]["TagColor"];
            matches: number;
            on: boolean;
        };
        Check: {
            id: string;
            name: string;
            description: string;
            builtIn: boolean;
            on: boolean;
        };
        CheckDetail: components["schemas"]["Check"] & {
            prompt: string;
            /** @enum {string} */
            sureness: "eager" | "balanced" | "careful";
            runsOn: string[];
            usedBy: string;
        };
        HealthOverview: {
            accounts: components["schemas"]["Account"][];
            searchIndex: string;
            meaningSearch: string;
            storage: string;
        };
        /** @description Mail the mirror keeps but does not show (ARCHITECTURE.md 4) */
        HiddenMail: {
            total: number;
            /** @description Hidden because the message moved to another folder, so it is still on the server */
            moved: number;
            /** @description Hidden because the server no longer holds the message */
            removed: number;
            /** @description Hidden by a pass that has not classified it yet. Not restorable and not counted by the mass-disable alert until a completed pass settles it. */
            pending: number;
        };
        RestoreResult: {
            restored: number;
        };
        OutboxAction: {
            /** @description The mirror row the action applies to */
            messageId: string;
            /** @enum {string} */
            action: "archive" | "trash" | "spam" | "not_junk" | "flag" | "unflag" | "seen" | "unseen" | "move" | "expunge";
            /** @description The destination folder for `move` (an undo sends the source folder back) */
            destinationFolderId?: string;
        };
        /** @description One outbox op, naming a postcondition rather than a command */
        OutboxItem: {
            id: string;
            accountId: string;
            /** @description The mirror row id, resolved from the content key and folder */
            messageId: string;
            seq?: number;
            /** @enum {string} */
            kind: "flags" | "move" | "expunge";
            /** @enum {string} */
            state: "pending" | "in_flight" | "done" | "failed" | "cancelled";
            sourceFolderId?: string;
            destinationFolderId?: string;
            flagsAdd?: string[];
            flagsClear?: string[];
            attempts: number;
            lastErrorCode?: string;
            lastErrorDetail?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        OutboxList: {
            active: components["schemas"]["OutboxItem"][];
            recent: components["schemas"]["OutboxItem"][];
        };
    };
    responses: {
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        MessageID: string;
        OutboxID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All databases reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
            /** @description One or more databases unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    updateAccountProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountProfile"];
            };
        };
        responses: {
            /** @description The updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listInbox: {
        parameters: {
            query?: {
                account_id?: string;
                folder?: "inbox" | "archive" | "trash" | "junk";
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the inbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inbox"];
                };
            };
        };
    };
    getMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailMessage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMessageSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listReading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingFeed"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked hits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description A cited answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskAnswer"];
                };
            };
            /** @description The monthly cap is reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The provider is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsOverview"];
                };
            };
        };
    };
    listPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description People */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"][];
                };
            };
        };
    };
    getPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The person */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    getRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listChecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"][];
                };
            };
        };
    };
    getCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMirrorHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOverview"];
                };
            };
        };
    };
    restoreMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored, or already visible */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description The message is pending classification (code pending_classification): a pass hid it but has not yet decided whether it moved or was removed. It stays hidden until the next completed pass settles it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    restoreAccountHidden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description How many rows were restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResult"];
                };
            };
        };
    };
    purgeMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Erased */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description The message is not hidden */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Event"];
                };
            };
            /** @description Too many streams are open (`too_many_streams`) or Ivy is shutting down (`unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOutbox: {
        parameters: {
            query?: {
                account_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live ops (the overlay) and recent terminal ones (history) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxList"];
                };
            };
        };
    };
    enqueueOutbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboxAction"];
            };
        };
        responses: {
            /** @description The action is queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxItem"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The action cannot be queued: `no_archive_folder` / `no_trash_folder` / `no_junk_folder` when the account has no folder for the role, `outbox_full` when the queue cap is reached, or `not_trash` when an expunge names a folder that is not the trash. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    dismissOutbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OutboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dismissed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description The op is still live */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    retryOutbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OutboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The op is queued again */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxItem"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The op is not failed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
