/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The running build version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process and database liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured accounts */
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename an account or choose its icon */
        patch: operations["updateAccountProfile"];
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox summaries, newest first */
        get: operations["listInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One message with its sanitized body */
        get: operations["getMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The header alone, for a failed body */
        get: operations["getMessageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Reading feed and its digest */
        get: operations["listReading"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hybrid keyword plus meaning search */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Ivy a question about the selected accounts */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User tags and placed tags */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Correspondents derived from the mirror */
        get: operations["listPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One correspondent */
        get: operations["getPerson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rules as plain sentences */
        get: operations["listRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One rule */
        get: operations["getRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Smart checks */
        get: operations["listChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One smart check */
        get: operations["getCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mirror/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-account sync state and index health */
        get: operations["getMirrorHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable code the UI maps to its own copy */
            code: string;
            message: string;
            detail?: string;
        };
        Version: {
            version: string;
        };
        Liveness: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            version: string;
            databases: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        TagColor: "sky" | "rose" | "teal" | "coral" | "lilac" | "mint" | "gold" | "sand" | "orchid" | "fern" | "slate" | "berry";
        /** @enum {integer} */
        AccountSlot: 1 | 2 | 3 | 4 | 5;
        /** @enum {string} */
        SyncState: "ok" | "syncing" | "auth-failed" | "unreachable";
        Account: {
            id: string;
            address: string;
            short: string;
            initial: string;
            /** @description The account's display name, empty when it has none */
            name: string;
            /** @description A chosen emoji or glyph, empty when it has none */
            icon: string;
            /** @description Whether GET /accounts/{id}/photo serves a photo */
            photo: boolean;
            slot: components["schemas"]["AccountSlot"];
            unread: number;
            smart: boolean;
            sync: components["schemas"]["SyncState"];
            syncNote: string;
            progress?: number;
        };
        /** @description A partial rename; omitted fields keep their current value */
        AccountProfile: {
            displayName?: string;
            icon?: string;
        };
        Attachment: {
            id: string;
            name: string;
            size: string;
            /** @enum {string} */
            kind: "image" | "file";
            /** @enum {string} */
            tone?: "a" | "b";
            failed?: boolean;
        };
        MailSummary: {
            id: string;
            accountId: string;
            from: string;
            initials: string;
            time: string;
            subject: string;
            preview: string;
            unread: boolean;
            needs: boolean;
            tag?: string;
        };
        MailMessage: {
            id: string;
            accountId: string;
            from: string;
            initials: string;
            time: string;
            subject: string;
            preview: string;
            unread: boolean;
            needs: boolean;
            tag?: string;
            toShort: string;
            toFull: string;
            summary?: string;
            /** @description Server-sanitised HTML body, safe to place in the reader's sandboxed frame. Empty for a message with no HTML part; use paragraphs then. */
            html?: string;
            paragraphs: string[];
            attachments: components["schemas"]["Attachment"][];
        };
        Inbox: {
            items: components["schemas"]["MailSummary"][];
            needCount: number;
            unreadCount: number;
            readingWaiting: number;
            nextCursor?: string;
        };
        Issue: {
            id: string;
            sender: string;
            initials: string;
            minutes?: number;
            read: boolean;
            title: string;
            blurb?: string;
        };
        ReadingFeed: {
            digest: string;
            issues: components["schemas"]["Issue"][];
        };
        SearchHit: {
            id: string;
            accountId: string;
            from: string;
            time: string;
            subject: string;
            preview: string;
            hasAttachment?: boolean;
            tag?: string;
            semantic?: boolean;
        };
        SearchResults: {
            query: string;
            total: number;
            hits: components["schemas"]["SearchHit"][];
            nextCursor?: string;
        };
        AskRequest: {
            question: string;
            accountIds?: string[];
        };
        AskStep: {
            /** @enum {string} */
            kind: "search" | "read" | "think";
            text: string;
        };
        AskSource: {
            n: number;
            subject: string;
            meta: string;
        };
        AskAnswer: {
            question: string;
            steps: components["schemas"]["AskStep"][];
            answer: string[];
            sources: components["schemas"]["AskSource"][];
        };
        UserTag: {
            id: string;
            name: string;
            color: components["schemas"]["TagColor"];
            count: number;
        };
        PlacedTag: {
            id: string;
            name: string;
            count: number;
        };
        TagsOverview: {
            mine: components["schemas"]["UserTag"][];
            placed: components["schemas"]["PlacedTag"][];
            activeRules: number;
        };
        Conversation: {
            id: string;
            subject: string;
            preview: string;
            when: string;
            unread?: boolean;
        };
        Person: {
            id: string;
            name: string;
            initials: string;
            email: string;
            slot: components["schemas"]["AccountSlot"];
            latest: string;
            when: string;
            writesTo: string;
            since: string;
            tags: string[];
            conversations: components["schemas"]["Conversation"][];
        };
        Rule: {
            id: string;
            when: string;
            whenToken?: string;
            whenTail?: string;
            then: string;
            thenToken: string;
            thenColor?: components["schemas"]["TagColor"];
            matches: number;
            on: boolean;
        };
        Check: {
            id: string;
            name: string;
            description: string;
            builtIn: boolean;
            on: boolean;
        };
        CheckDetail: components["schemas"]["Check"] & {
            prompt: string;
            /** @enum {string} */
            sureness: "eager" | "balanced" | "careful";
            runsOn: string[];
            usedBy: string;
        };
        HealthOverview: {
            accounts: components["schemas"]["Account"][];
            searchIndex: string;
            meaningSearch: string;
            storage: string;
        };
    };
    responses: {
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        MessageID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All databases reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
            /** @description One or more databases unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    updateAccountProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountProfile"];
            };
        };
        responses: {
            /** @description The updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listInbox: {
        parameters: {
            query?: {
                account_id?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the inbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inbox"];
                };
            };
        };
    };
    getMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailMessage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMessageSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listReading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingFeed"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked hits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description A cited answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskAnswer"];
                };
            };
            /** @description The monthly cap is reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The provider is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsOverview"];
                };
            };
        };
    };
    listPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description People */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"][];
                };
            };
        };
    };
    getPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The person */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    getRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listChecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"][];
                };
            };
        };
    };
    getCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMirrorHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOverview"];
                };
            };
        };
    };
}
