// Every screen and designed state, by name. The smoke spec visits each on phone and desktop,
// fails on any console error, and saves a screenshot to web/shots/ for a human to look at.
export const ROUTES: Record<string, string> = {
	'inbox': '/',
	'inbox-empty': '/?scenario=empty',
	'inbox-sync-error': '/?scenario=sync-error',
	'offline': '/?scenario=offline',
	'message': '/m/m1',
	'message-fetch-error': '/m/m1?scenario=fetch-error',
	'message-attachment-error': '/m/m1?scenario=attachment-error',
	'reading': '/reading',
	'search': '/search?q=domain+renewal',
	'search-none': '/search?q=xylophone+invoice',
	'ask': '/ask?q=When+does+my+domain+renew%3F',
	'ask-limit': '/ask?q=hello&scenario=limit',
	'ask-provider-down': '/ask?q=hello&scenario=provider-down',
	'tags': '/tags',
	'tags-new': '/tags?new',
	'tag-edit': '/tags/t1',
	'people': '/people',
	'person': '/people/p-ml',
	'rules': '/rules',
	'rule-new': '/rules/new',
	'rule-review': '/rules/new/review',
	'rule-edit': '/rules/r1',
	'checks': '/checks',
	'check': '/checks/k1',
	'compose': '/compose?reply=m1',
	'compose-new': '/compose',
	'compose-attach': '/compose?reply=m1&attach',
	'compose-send-failed': '/compose?reply=m1&scenario=send-failed',
	'drafts': '/drafts',
	'settings': '/settings',
	'account-profile': '/settings/account/a1',
	'mirror-health': '/settings/health',
	'outbox': '/settings/outbox',
	'spend': '/settings/spend',
	'spend-none': '/settings/spend?scenario=no-spend',
	'spend-cap': '/settings/spend?scenario=cap-hit',
	'spend-calls': '/settings/spend/calls',
	'spend-calls-none': '/settings/spend/calls?scenario=no-spend',
	'welcome': '/welcome',
	'welcome-account': '/welcome/account',
	'gallery': '/gallery',
	'not-found': '/nope'
};
