// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AccountSlot.
const (
	N1 AccountSlot = 1
	N2 AccountSlot = 2
	N3 AccountSlot = 3
	N4 AccountSlot = 4
	N5 AccountSlot = 5
)

// Valid indicates whether the value is a known member of the AccountSlot enum.
func (e AccountSlot) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	case N4:
		return true
	case N5:
		return true
	default:
		return false
	}
}

// Defines values for AskStepKind.
const (
	Read   AskStepKind = "read"
	Search AskStepKind = "search"
	Think  AskStepKind = "think"
)

// Valid indicates whether the value is a known member of the AskStepKind enum.
func (e AskStepKind) Valid() bool {
	switch e {
	case Read:
		return true
	case Search:
		return true
	case Think:
		return true
	default:
		return false
	}
}

// Defines values for AttachmentKind.
const (
	File  AttachmentKind = "file"
	Image AttachmentKind = "image"
)

// Valid indicates whether the value is a known member of the AttachmentKind enum.
func (e AttachmentKind) Valid() bool {
	switch e {
	case File:
		return true
	case Image:
		return true
	default:
		return false
	}
}

// Defines values for AttachmentTone.
const (
	A AttachmentTone = "a"
	B AttachmentTone = "b"
)

// Valid indicates whether the value is a known member of the AttachmentTone enum.
func (e AttachmentTone) Valid() bool {
	switch e {
	case A:
		return true
	case B:
		return true
	default:
		return false
	}
}

// Defines values for CheckDetailSureness.
const (
	Balanced CheckDetailSureness = "balanced"
	Careful  CheckDetailSureness = "careful"
	Eager    CheckDetailSureness = "eager"
)

// Valid indicates whether the value is a known member of the CheckDetailSureness enum.
func (e CheckDetailSureness) Valid() bool {
	switch e {
	case Balanced:
		return true
	case Careful:
		return true
	case Eager:
		return true
	default:
		return false
	}
}

// Defines values for EventType.
const (
	EventTypeFolderChanged  EventType = "folder.changed"
	EventTypeHealthAlert    EventType = "health.alert"
	EventTypeMessageChanged EventType = "message.changed"
	EventTypeOutboxState    EventType = "outbox.state"
	EventTypeSyncState      EventType = "sync.state"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case EventTypeFolderChanged:
		return true
	case EventTypeHealthAlert:
		return true
	case EventTypeMessageChanged:
		return true
	case EventTypeOutboxState:
		return true
	case EventTypeSyncState:
		return true
	default:
		return false
	}
}

// Defines values for LivenessStatus.
const (
	LivenessStatusOk          LivenessStatus = "ok"
	LivenessStatusUnavailable LivenessStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the LivenessStatus enum.
func (e LivenessStatus) Valid() bool {
	switch e {
	case LivenessStatusOk:
		return true
	case LivenessStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for SyncState.
const (
	SyncStateAuthFailed  SyncState = "auth-failed"
	SyncStateOk          SyncState = "ok"
	SyncStateSyncing     SyncState = "syncing"
	SyncStateUnreachable SyncState = "unreachable"
)

// Valid indicates whether the value is a known member of the SyncState enum.
func (e SyncState) Valid() bool {
	switch e {
	case SyncStateAuthFailed:
		return true
	case SyncStateOk:
		return true
	case SyncStateSyncing:
		return true
	case SyncStateUnreachable:
		return true
	default:
		return false
	}
}

// Defines values for TagColor.
const (
	Berry  TagColor = "berry"
	Coral  TagColor = "coral"
	Fern   TagColor = "fern"
	Gold   TagColor = "gold"
	Lilac  TagColor = "lilac"
	Mint   TagColor = "mint"
	Orchid TagColor = "orchid"
	Rose   TagColor = "rose"
	Sand   TagColor = "sand"
	Sky    TagColor = "sky"
	Slate  TagColor = "slate"
	Teal   TagColor = "teal"
)

// Valid indicates whether the value is a known member of the TagColor enum.
func (e TagColor) Valid() bool {
	switch e {
	case Berry:
		return true
	case Coral:
		return true
	case Fern:
		return true
	case Gold:
		return true
	case Lilac:
		return true
	case Mint:
		return true
	case Orchid:
		return true
	case Rose:
		return true
	case Sand:
		return true
	case Sky:
		return true
	case Slate:
		return true
	case Teal:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Address string `json:"address"`

	// Icon A chosen emoji or glyph, empty when it has none
	Icon    string `json:"icon"`
	Id      string `json:"id"`
	Initial string `json:"initial"`

	// Name The account's display name, empty when it has none
	Name string `json:"name"`

	// Photo Whether GET /accounts/{id}/photo serves a photo
	Photo    bool        `json:"photo"`
	Progress *float32    `json:"progress,omitempty"`
	Short    string      `json:"short"`
	Slot     AccountSlot `json:"slot"`
	Smart    bool        `json:"smart"`
	Sync     SyncState   `json:"sync"`

	// SyncNote What the sync is doing, as a short phrase with no time in it ("Up to date", "Reading your mailbox, newest first"). The browser appends "synced 4 min ago" from syncedAt.
	SyncNote string `json:"syncNote"`

	// SyncedAt When the account's mailbox last synced, RFC 3339 in UTC. Absent until the first folder has synced.
	SyncedAt *time.Time `json:"syncedAt,omitempty"`
	Unread   int        `json:"unread"`
}

// AccountProfile A partial rename; omitted fields keep their current value
type AccountProfile struct {
	DisplayName *string `json:"displayName,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

// AccountSlot defines model for AccountSlot.
type AccountSlot int

// AskAnswer defines model for AskAnswer.
type AskAnswer struct {
	Answer   []string    `json:"answer"`
	Question string      `json:"question"`
	Sources  []AskSource `json:"sources"`
	Steps    []AskStep   `json:"steps"`
}

// AskRequest defines model for AskRequest.
type AskRequest struct {
	AccountIds *[]string `json:"accountIds,omitempty"`
	Question   string    `json:"question"`
}

// AskSource defines model for AskSource.
type AskSource struct {
	Meta    string `json:"meta"`
	N       int    `json:"n"`
	Subject string `json:"subject"`
}

// AskStep defines model for AskStep.
type AskStep struct {
	Kind AskStepKind `json:"kind"`
	Text string      `json:"text"`
}

// AskStepKind defines model for AskStep.Kind.
type AskStepKind string

// Attachment defines model for Attachment.
type Attachment struct {
	Failed *bool           `json:"failed,omitempty"`
	Id     string          `json:"id"`
	Kind   AttachmentKind  `json:"kind"`
	Name   string          `json:"name"`
	Size   string          `json:"size"`
	Tone   *AttachmentTone `json:"tone,omitempty"`
}

// AttachmentKind defines model for Attachment.Kind.
type AttachmentKind string

// AttachmentTone defines model for Attachment.Tone.
type AttachmentTone string

// Check defines model for Check.
type Check struct {
	BuiltIn     bool   `json:"builtIn"`
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	On          bool   `json:"on"`
}

// CheckDetail defines model for CheckDetail.
type CheckDetail struct {
	BuiltIn     bool                `json:"builtIn"`
	Description string              `json:"description"`
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	On          bool                `json:"on"`
	Prompt      string              `json:"prompt"`
	RunsOn      []string            `json:"runsOn"`
	Sureness    CheckDetailSureness `json:"sureness"`
	UsedBy      string              `json:"usedBy"`
}

// CheckDetailSureness defines model for CheckDetail.Sureness.
type CheckDetailSureness string

// Conversation defines model for Conversation.
type Conversation struct {
	Id      string `json:"id"`
	Preview string `json:"preview"`
	Subject string `json:"subject"`
	Unread  *bool  `json:"unread,omitempty"`
	When    string `json:"when"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable code the UI maps to its own copy
	Code    string  `json:"code"`
	Detail  *string `json:"detail,omitempty"`
	Message string  `json:"message"`
}

// Event One hint on the event stream. It says what changed, never the new value.
type Event struct {
	AccountId *string `json:"accountId,omitempty"`

	// Code Stable reason, used by health.alert
	Code   *string   `json:"code,omitempty"`
	Folder *string   `json:"folder,omitempty"`
	Type   EventType `json:"type"`
}

// EventType defines model for Event.Type.
type EventType string

// HealthOverview defines model for HealthOverview.
type HealthOverview struct {
	Accounts      []Account `json:"accounts"`
	MeaningSearch string    `json:"meaningSearch"`
	SearchIndex   string    `json:"searchIndex"`
	Storage       string    `json:"storage"`
}

// Inbox defines model for Inbox.
type Inbox struct {
	Items          []MailSummary `json:"items"`
	NeedCount      int           `json:"needCount"`
	NextCursor     *string       `json:"nextCursor,omitempty"`
	ReadingWaiting int           `json:"readingWaiting"`
	UnreadCount    int           `json:"unreadCount"`
}

// Issue defines model for Issue.
type Issue struct {
	Blurb    *string `json:"blurb,omitempty"`
	Id       string  `json:"id"`
	Initials string  `json:"initials"`
	Minutes  *int    `json:"minutes,omitempty"`
	Read     bool    `json:"read"`
	Sender   string  `json:"sender"`
	Title    string  `json:"title"`
}

// Liveness defines model for Liveness.
type Liveness struct {
	Databases map[string]string `json:"databases"`
	Status    LivenessStatus    `json:"status"`
	Version   string            `json:"version"`
}

// LivenessStatus defines model for Liveness.Status.
type LivenessStatus string

// MailMessage defines model for MailMessage.
type MailMessage struct {
	AccountId   string       `json:"accountId"`
	Attachments []Attachment `json:"attachments"`

	// Date The message's instant, RFC 3339 in UTC (see MailSummary).
	Date time.Time `json:"date"`
	From string    `json:"from"`

	// Html Server-sanitised HTML body, safe to place in the reader's sandboxed frame. Empty for a message with no HTML part; use paragraphs then.
	Html       *string  `json:"html,omitempty"`
	Id         string   `json:"id"`
	Initials   string   `json:"initials"`
	Needs      bool     `json:"needs"`
	Paragraphs []string `json:"paragraphs"`
	Preview    string   `json:"preview"`
	Subject    string   `json:"subject"`
	Summary    *string  `json:"summary,omitempty"`
	Tag        *string  `json:"tag,omitempty"`
	ToFull     string   `json:"toFull"`
	ToShort    string   `json:"toShort"`
	Unread     bool     `json:"unread"`
}

// MailSummary defines model for MailSummary.
type MailSummary struct {
	AccountId string `json:"accountId"`

	// Date The message's instant, RFC 3339 in UTC. The browser formats it in the viewer's own zone and locale; a message with no Date header carries the zero instant (0001-01-01T00:00:00Z) and shows no time.
	Date     time.Time `json:"date"`
	From     string    `json:"from"`
	Id       string    `json:"id"`
	Initials string    `json:"initials"`
	Needs    bool      `json:"needs"`
	Preview  string    `json:"preview"`
	Subject  string    `json:"subject"`
	Tag      *string   `json:"tag,omitempty"`
	Unread   bool      `json:"unread"`
}

// Person defines model for Person.
type Person struct {
	Conversations []Conversation `json:"conversations"`
	Email         string         `json:"email"`
	Id            string         `json:"id"`
	Initials      string         `json:"initials"`
	Latest        string         `json:"latest"`
	Name          string         `json:"name"`
	Since         string         `json:"since"`
	Slot          AccountSlot    `json:"slot"`
	Tags          []string       `json:"tags"`
	When          string         `json:"when"`
	WritesTo      string         `json:"writesTo"`
}

// PlacedTag defines model for PlacedTag.
type PlacedTag struct {
	Count int    `json:"count"`
	Id    string `json:"id"`
	Name  string `json:"name"`
}

// ReadingFeed defines model for ReadingFeed.
type ReadingFeed struct {
	Digest string  `json:"digest"`
	Issues []Issue `json:"issues"`
}

// Rule defines model for Rule.
type Rule struct {
	Id        string    `json:"id"`
	Matches   int       `json:"matches"`
	On        bool      `json:"on"`
	Then      string    `json:"then"`
	ThenColor *TagColor `json:"thenColor,omitempty"`
	ThenToken string    `json:"thenToken"`
	When      string    `json:"when"`
	WhenTail  *string   `json:"whenTail,omitempty"`
	WhenToken *string   `json:"whenToken,omitempty"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	AccountId string `json:"accountId"`

	// Date The message's instant, RFC 3339 in UTC (see MailSummary).
	Date          time.Time `json:"date"`
	From          string    `json:"from"`
	HasAttachment *bool     `json:"hasAttachment,omitempty"`
	Id            string    `json:"id"`
	Preview       string    `json:"preview"`
	Semantic      *bool     `json:"semantic,omitempty"`
	Subject       string    `json:"subject"`
	Tag           *string   `json:"tag,omitempty"`
}

// SearchResults defines model for SearchResults.
type SearchResults struct {
	Hits       []SearchHit `json:"hits"`
	NextCursor *string     `json:"nextCursor,omitempty"`
	Query      string      `json:"query"`
	Total      int         `json:"total"`
}

// SyncState defines model for SyncState.
type SyncState string

// TagColor defines model for TagColor.
type TagColor string

// TagsOverview defines model for TagsOverview.
type TagsOverview struct {
	ActiveRules int         `json:"activeRules"`
	Mine        []UserTag   `json:"mine"`
	Placed      []PlacedTag `json:"placed"`
}

// UserTag defines model for UserTag.
type UserTag struct {
	Color TagColor `json:"color"`
	Count int      `json:"count"`
	Id    string   `json:"id"`
	Name  string   `json:"name"`
}

// Version defines model for Version.
type Version struct {
	Version string `json:"version"`
}

// MessageID defines model for MessageID.
type MessageID = string

// NotFound defines model for NotFound.
type NotFound = Error

// ListInboxParams defines parameters for ListInbox.
type ListInboxParams struct {
	AccountId *string `form:"account_id,omitempty" json:"account_id,omitempty"`
	Cursor    *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q      string  `form:"q" json:"q"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UpdateAccountProfileJSONRequestBody defines body for UpdateAccountProfile for application/json ContentType.
type UpdateAccountProfileJSONRequestBody = AccountProfile

// AskJSONRequestBody defines body for Ask for application/json ContentType.
type AskJSONRequestBody = AskRequest
