// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AccountSlot.
const (
	N1 AccountSlot = 1
	N2 AccountSlot = 2
	N3 AccountSlot = 3
	N4 AccountSlot = 4
	N5 AccountSlot = 5
)

// Valid indicates whether the value is a known member of the AccountSlot enum.
func (e AccountSlot) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	case N4:
		return true
	case N5:
		return true
	default:
		return false
	}
}

// Defines values for AskStepKind.
const (
	Read   AskStepKind = "read"
	Search AskStepKind = "search"
	Think  AskStepKind = "think"
)

// Valid indicates whether the value is a known member of the AskStepKind enum.
func (e AskStepKind) Valid() bool {
	switch e {
	case Read:
		return true
	case Search:
		return true
	case Think:
		return true
	default:
		return false
	}
}

// Defines values for AttachmentKind.
const (
	File  AttachmentKind = "file"
	Image AttachmentKind = "image"
)

// Valid indicates whether the value is a known member of the AttachmentKind enum.
func (e AttachmentKind) Valid() bool {
	switch e {
	case File:
		return true
	case Image:
		return true
	default:
		return false
	}
}

// Defines values for AttachmentTone.
const (
	A AttachmentTone = "a"
	B AttachmentTone = "b"
)

// Valid indicates whether the value is a known member of the AttachmentTone enum.
func (e AttachmentTone) Valid() bool {
	switch e {
	case A:
		return true
	case B:
		return true
	default:
		return false
	}
}

// Defines values for CheckDetailSureness.
const (
	Balanced CheckDetailSureness = "balanced"
	Careful  CheckDetailSureness = "careful"
	Eager    CheckDetailSureness = "eager"
)

// Valid indicates whether the value is a known member of the CheckDetailSureness enum.
func (e CheckDetailSureness) Valid() bool {
	switch e {
	case Balanced:
		return true
	case Careful:
		return true
	case Eager:
		return true
	default:
		return false
	}
}

// Defines values for EventType.
const (
	EventTypeFolderChanged  EventType = "folder.changed"
	EventTypeHealthAlert    EventType = "health.alert"
	EventTypeMessageChanged EventType = "message.changed"
	EventTypeOutboxState    EventType = "outbox.state"
	EventTypeSyncState      EventType = "sync.state"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case EventTypeFolderChanged:
		return true
	case EventTypeHealthAlert:
		return true
	case EventTypeMessageChanged:
		return true
	case EventTypeOutboxState:
		return true
	case EventTypeSyncState:
		return true
	default:
		return false
	}
}

// Defines values for LivenessStatus.
const (
	LivenessStatusOk          LivenessStatus = "ok"
	LivenessStatusUnavailable LivenessStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the LivenessStatus enum.
func (e LivenessStatus) Valid() bool {
	switch e {
	case LivenessStatusOk:
		return true
	case LivenessStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for OutboxActionAction.
const (
	OutboxActionArchive OutboxActionAction = "archive"
	OutboxActionExpunge OutboxActionAction = "expunge"
	OutboxActionFlag    OutboxActionAction = "flag"
	OutboxActionMove    OutboxActionAction = "move"
	OutboxActionNotJunk OutboxActionAction = "not_junk"
	OutboxActionSeen    OutboxActionAction = "seen"
	OutboxActionSpam    OutboxActionAction = "spam"
	OutboxActionTag     OutboxActionAction = "tag"
	OutboxActionTrash   OutboxActionAction = "trash"
	OutboxActionUnflag  OutboxActionAction = "unflag"
	OutboxActionUnseen  OutboxActionAction = "unseen"
	OutboxActionUntag   OutboxActionAction = "untag"
)

// Valid indicates whether the value is a known member of the OutboxActionAction enum.
func (e OutboxActionAction) Valid() bool {
	switch e {
	case OutboxActionArchive:
		return true
	case OutboxActionExpunge:
		return true
	case OutboxActionFlag:
		return true
	case OutboxActionMove:
		return true
	case OutboxActionNotJunk:
		return true
	case OutboxActionSeen:
		return true
	case OutboxActionSpam:
		return true
	case OutboxActionTag:
		return true
	case OutboxActionTrash:
		return true
	case OutboxActionUnflag:
		return true
	case OutboxActionUnseen:
		return true
	case OutboxActionUntag:
		return true
	default:
		return false
	}
}

// Defines values for OutboxItemKind.
const (
	OutboxKindExpunge OutboxItemKind = "expunge"
	OutboxKindFlags   OutboxItemKind = "flags"
	OutboxKindMove    OutboxItemKind = "move"
)

// Valid indicates whether the value is a known member of the OutboxItemKind enum.
func (e OutboxItemKind) Valid() bool {
	switch e {
	case OutboxKindExpunge:
		return true
	case OutboxKindFlags:
		return true
	case OutboxKindMove:
		return true
	default:
		return false
	}
}

// Defines values for OutboxItemState.
const (
	OutboxStateCancelled OutboxItemState = "cancelled"
	OutboxStateDone      OutboxItemState = "done"
	OutboxStateFailed    OutboxItemState = "failed"
	OutboxStateInFlight  OutboxItemState = "in_flight"
	OutboxStatePending   OutboxItemState = "pending"
)

// Valid indicates whether the value is a known member of the OutboxItemState enum.
func (e OutboxItemState) Valid() bool {
	switch e {
	case OutboxStateCancelled:
		return true
	case OutboxStateDone:
		return true
	case OutboxStateFailed:
		return true
	case OutboxStateInFlight:
		return true
	case OutboxStatePending:
		return true
	default:
		return false
	}
}

// Defines values for RuleActionSnooze.
const (
	RuleActionSnoozeLaterToday RuleActionSnooze = "later_today"
	RuleActionSnoozeNextWeek   RuleActionSnooze = "next_week"
	RuleActionSnoozeTomorrow   RuleActionSnooze = "tomorrow"
	RuleActionSnoozeWeekend    RuleActionSnooze = "weekend"
)

// Valid indicates whether the value is a known member of the RuleActionSnooze enum.
func (e RuleActionSnooze) Valid() bool {
	switch e {
	case RuleActionSnoozeLaterToday:
		return true
	case RuleActionSnoozeNextWeek:
		return true
	case RuleActionSnoozeTomorrow:
		return true
	case RuleActionSnoozeWeekend:
		return true
	default:
		return false
	}
}

// Defines values for RuleActionType.
const (
	Reading RuleActionType = "reading"
	Snooze  RuleActionType = "snooze"
	Tag     RuleActionType = "tag"
)

// Valid indicates whether the value is a known member of the RuleActionType enum.
func (e RuleActionType) Valid() bool {
	switch e {
	case Reading:
		return true
	case Snooze:
		return true
	case Tag:
		return true
	default:
		return false
	}
}

// Defines values for RuleConditionField.
const (
	RuleConditionFieldAccount       RuleConditionField = "account"
	RuleConditionFieldFrom          RuleConditionField = "from"
	RuleConditionFieldHasAttachment RuleConditionField = "has_attachment"
	RuleConditionFieldSubject       RuleConditionField = "subject"
)

// Valid indicates whether the value is a known member of the RuleConditionField enum.
func (e RuleConditionField) Valid() bool {
	switch e {
	case RuleConditionFieldAccount:
		return true
	case RuleConditionFieldFrom:
		return true
	case RuleConditionFieldHasAttachment:
		return true
	case RuleConditionFieldSubject:
		return true
	default:
		return false
	}
}

// Defines values for SnoozeRequestPreset.
const (
	SnoozeRequestPresetLaterToday SnoozeRequestPreset = "later_today"
	SnoozeRequestPresetNextWeek   SnoozeRequestPreset = "next_week"
	SnoozeRequestPresetTomorrow   SnoozeRequestPreset = "tomorrow"
	SnoozeRequestPresetWeekend    SnoozeRequestPreset = "weekend"
)

// Valid indicates whether the value is a known member of the SnoozeRequestPreset enum.
func (e SnoozeRequestPreset) Valid() bool {
	switch e {
	case SnoozeRequestPresetLaterToday:
		return true
	case SnoozeRequestPresetNextWeek:
		return true
	case SnoozeRequestPresetTomorrow:
		return true
	case SnoozeRequestPresetWeekend:
		return true
	default:
		return false
	}
}

// Defines values for SyncState.
const (
	SyncStateAuthFailed  SyncState = "auth-failed"
	SyncStateOk          SyncState = "ok"
	SyncStateSyncing     SyncState = "syncing"
	SyncStateUnreachable SyncState = "unreachable"
)

// Valid indicates whether the value is a known member of the SyncState enum.
func (e SyncState) Valid() bool {
	switch e {
	case SyncStateAuthFailed:
		return true
	case SyncStateOk:
		return true
	case SyncStateSyncing:
		return true
	case SyncStateUnreachable:
		return true
	default:
		return false
	}
}

// Defines values for TagColor.
const (
	Berry  TagColor = "berry"
	Coral  TagColor = "coral"
	Fern   TagColor = "fern"
	Gold   TagColor = "gold"
	Lilac  TagColor = "lilac"
	Mint   TagColor = "mint"
	Orchid TagColor = "orchid"
	Rose   TagColor = "rose"
	Sand   TagColor = "sand"
	Sky    TagColor = "sky"
	Slate  TagColor = "slate"
	Teal   TagColor = "teal"
)

// Valid indicates whether the value is a known member of the TagColor enum.
func (e TagColor) Valid() bool {
	switch e {
	case Berry:
		return true
	case Coral:
		return true
	case Fern:
		return true
	case Gold:
		return true
	case Lilac:
		return true
	case Mint:
		return true
	case Orchid:
		return true
	case Rose:
		return true
	case Sand:
		return true
	case Sky:
		return true
	case Slate:
		return true
	case Teal:
		return true
	default:
		return false
	}
}

// Defines values for ListInboxParamsFolder.
const (
	ListInboxParamsFolderArchive ListInboxParamsFolder = "archive"
	ListInboxParamsFolderInbox   ListInboxParamsFolder = "inbox"
	ListInboxParamsFolderJunk    ListInboxParamsFolder = "junk"
	ListInboxParamsFolderSnoozed ListInboxParamsFolder = "snoozed"
	ListInboxParamsFolderTrash   ListInboxParamsFolder = "trash"
)

// Valid indicates whether the value is a known member of the ListInboxParamsFolder enum.
func (e ListInboxParamsFolder) Valid() bool {
	switch e {
	case ListInboxParamsFolderArchive:
		return true
	case ListInboxParamsFolderInbox:
		return true
	case ListInboxParamsFolderJunk:
		return true
	case ListInboxParamsFolderSnoozed:
		return true
	case ListInboxParamsFolderTrash:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Address string `json:"address"`

	// Hidden Mail the mirror keeps but does not show (ARCHITECTURE.md 4)
	Hidden *HiddenMail `json:"hidden,omitempty"`

	// Icon A chosen emoji or glyph, empty when it has none
	Icon    string `json:"icon"`
	Id      string `json:"id"`
	Initial string `json:"initial"`

	// Name The account's display name, empty when it has none
	Name string `json:"name"`

	// Photo Whether GET /accounts/{id}/photo serves a photo
	Photo    bool        `json:"photo"`
	Progress *float32    `json:"progress,omitempty"`
	Short    string      `json:"short"`
	Slot     AccountSlot `json:"slot"`
	Smart    bool        `json:"smart"`
	Sync     SyncState   `json:"sync"`

	// SyncNote What the sync is doing, as a short phrase with no time in it ("Up to date", "Reading your mailbox, newest first"). The browser appends "synced 4 min ago" from syncedAt.
	SyncNote string `json:"syncNote"`

	// SyncedAt When the account's mailbox last synced, RFC 3339 in UTC. Absent until the first folder has synced.
	SyncedAt *time.Time `json:"syncedAt,omitempty"`
	Unread   int        `json:"unread"`
}

// AccountProfile A partial rename; omitted fields keep their current value
type AccountProfile struct {
	DisplayName *string `json:"displayName,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

// AccountSlot defines model for AccountSlot.
type AccountSlot int

// AskAnswer defines model for AskAnswer.
type AskAnswer struct {
	Answer   []string    `json:"answer"`
	Question string      `json:"question"`
	Sources  []AskSource `json:"sources"`
	Steps    []AskStep   `json:"steps"`
}

// AskRequest defines model for AskRequest.
type AskRequest struct {
	AccountIds *[]string `json:"accountIds,omitempty"`
	Question   string    `json:"question"`
}

// AskSource defines model for AskSource.
type AskSource struct {
	Meta    string `json:"meta"`
	N       int    `json:"n"`
	Subject string `json:"subject"`
}

// AskStep defines model for AskStep.
type AskStep struct {
	Kind AskStepKind `json:"kind"`
	Text string      `json:"text"`
}

// AskStepKind defines model for AskStep.Kind.
type AskStepKind string

// Attachment defines model for Attachment.
type Attachment struct {
	Failed *bool           `json:"failed,omitempty"`
	Id     string          `json:"id"`
	Kind   AttachmentKind  `json:"kind"`
	Name   string          `json:"name"`
	Size   string          `json:"size"`
	Tone   *AttachmentTone `json:"tone,omitempty"`
}

// AttachmentKind defines model for Attachment.Kind.
type AttachmentKind string

// AttachmentTone defines model for Attachment.Tone.
type AttachmentTone string

// Check defines model for Check.
type Check struct {
	BuiltIn     bool   `json:"builtIn"`
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	On          bool   `json:"on"`
}

// CheckDetail defines model for CheckDetail.
type CheckDetail struct {
	BuiltIn     bool                `json:"builtIn"`
	Description string              `json:"description"`
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	On          bool                `json:"on"`
	Prompt      string              `json:"prompt"`
	RunsOn      []string            `json:"runsOn"`
	Sureness    CheckDetailSureness `json:"sureness"`
	UsedBy      string              `json:"usedBy"`
}

// CheckDetailSureness defines model for CheckDetail.Sureness.
type CheckDetailSureness string

// Conversation defines model for Conversation.
type Conversation struct {
	Id      string `json:"id"`
	Preview string `json:"preview"`
	Subject string `json:"subject"`
	Unread  *bool  `json:"unread,omitempty"`
	When    string `json:"when"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable code the UI maps to its own copy
	Code    string  `json:"code"`
	Detail  *string `json:"detail,omitempty"`
	Message string  `json:"message"`
}

// Event One hint on the event stream. It says what changed, never the new value.
type Event struct {
	AccountId *string `json:"accountId,omitempty"`

	// Code Stable reason, used by health.alert
	Code   *string   `json:"code,omitempty"`
	Folder *string   `json:"folder,omitempty"`
	Type   EventType `json:"type"`
}

// EventType defines model for Event.Type.
type EventType string

// HealthOverview defines model for HealthOverview.
type HealthOverview struct {
	Accounts      []Account `json:"accounts"`
	MeaningSearch string    `json:"meaningSearch"`
	SearchIndex   string    `json:"searchIndex"`
	Storage       string    `json:"storage"`
}

// HiddenMail Mail the mirror keeps but does not show (ARCHITECTURE.md 4)
type HiddenMail struct {
	// Moved Hidden because the message moved to another folder, so it is still on the server
	Moved int `json:"moved"`

	// Pending Hidden by a pass that has not classified it yet. Not restorable and not counted by the mass-disable alert until a completed pass settles it.
	Pending int `json:"pending"`

	// Removed Hidden because the server no longer holds the message
	Removed int `json:"removed"`
	Total   int `json:"total"`
}

// Inbox defines model for Inbox.
type Inbox struct {
	Items          []MailSummary `json:"items"`
	NeedCount      int           `json:"needCount"`
	NextCursor     *string       `json:"nextCursor,omitempty"`
	ReadingWaiting int           `json:"readingWaiting"`
	UnreadCount    int           `json:"unreadCount"`
}

// Issue defines model for Issue.
type Issue struct {
	Blurb    *string `json:"blurb,omitempty"`
	Id       string  `json:"id"`
	Initials string  `json:"initials"`
	Minutes  *int    `json:"minutes,omitempty"`
	Read     bool    `json:"read"`
	Sender   string  `json:"sender"`
	Title    string  `json:"title"`
}

// Liveness defines model for Liveness.
type Liveness struct {
	Databases map[string]string `json:"databases"`
	Status    LivenessStatus    `json:"status"`
	Version   string            `json:"version"`
}

// LivenessStatus defines model for Liveness.Status.
type LivenessStatus string

// MailMessage defines model for MailMessage.
type MailMessage struct {
	AccountId   string       `json:"accountId"`
	Attachments []Attachment `json:"attachments"`

	// Date The message's instant, RFC 3339 in UTC (see MailSummary).
	Date time.Time `json:"date"`

	// Flagged Whether the message carries the \\Flagged keyword
	Flagged *bool  `json:"flagged,omitempty"`
	From    string `json:"from"`

	// Html Server-sanitised HTML body, safe to place in the reader's sandboxed frame. Empty for a message with no HTML part; use paragraphs then.
	Html       *string  `json:"html,omitempty"`
	Id         string   `json:"id"`
	Initials   string   `json:"initials"`
	Needs      bool     `json:"needs"`
	Paragraphs []string `json:"paragraphs"`
	Preview    string   `json:"preview"`
	Subject    string   `json:"subject"`
	Summary    *string  `json:"summary,omitempty"`
	Tag        *string  `json:"tag,omitempty"`

	// TagIds Every tag the message is in, for the tag picker; `tag` is the first by name
	TagIds  *[]string `json:"tagIds,omitempty"`
	ToFull  string    `json:"toFull"`
	ToShort string    `json:"toShort"`
	Unread  bool      `json:"unread"`
}

// MailSummary defines model for MailSummary.
type MailSummary struct {
	AccountId string `json:"accountId"`

	// Date The message's instant, RFC 3339 in UTC. The browser formats it in the viewer's own zone and locale; a message with no Date header carries the zero instant (0001-01-01T00:00:00Z) and shows no time.
	Date time.Time `json:"date"`

	// Flagged Whether the message carries the \\Flagged keyword
	Flagged  *bool   `json:"flagged,omitempty"`
	From     string  `json:"from"`
	Id       string  `json:"id"`
	Initials string  `json:"initials"`
	Needs    bool    `json:"needs"`
	Preview  string  `json:"preview"`
	Subject  string  `json:"subject"`
	Tag      *string `json:"tag,omitempty"`
	Unread   bool    `json:"unread"`
}

// OutboxAction defines model for OutboxAction.
type OutboxAction struct {
	Action OutboxActionAction `json:"action"`

	// DestinationFolderId The destination folder for `move` (an undo sends the source folder back)
	DestinationFolderId *string `json:"destinationFolderId,omitempty"`

	// MessageId The mirror row the action applies to
	MessageId string `json:"messageId"`

	// TagId The tag for `tag` and `untag`. Tagging is the `$ivy-<slug>` keyword written to the server; `untag` clears it from every live copy of the message.
	TagId *string `json:"tagId,omitempty"`
}

// OutboxActionAction defines model for OutboxAction.Action.
type OutboxActionAction string

// OutboxItem One outbox op, naming a postcondition rather than a command
type OutboxItem struct {
	AccountId           string         `json:"accountId"`
	Attempts            int            `json:"attempts"`
	CompletedAt         *time.Time     `json:"completedAt,omitempty"`
	CreatedAt           time.Time      `json:"createdAt"`
	DestinationFolderId *string        `json:"destinationFolderId,omitempty"`
	FlagsAdd            *[]string      `json:"flagsAdd,omitempty"`
	FlagsClear          *[]string      `json:"flagsClear,omitempty"`
	Id                  string         `json:"id"`
	Kind                OutboxItemKind `json:"kind"`
	LastErrorCode       *string        `json:"lastErrorCode,omitempty"`
	LastErrorDetail     *string        `json:"lastErrorDetail,omitempty"`

	// MessageId The mirror row id, resolved from the content key and folder
	MessageId      string          `json:"messageId"`
	Seq            *int            `json:"seq,omitempty"`
	SourceFolderId *string         `json:"sourceFolderId,omitempty"`
	State          OutboxItemState `json:"state"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}

// OutboxItemKind defines model for OutboxItem.Kind.
type OutboxItemKind string

// OutboxItemState defines model for OutboxItem.State.
type OutboxItemState string

// OutboxList defines model for OutboxList.
type OutboxList struct {
	Active []OutboxItem `json:"active"`
	Recent []OutboxItem `json:"recent"`
}

// Person defines model for Person.
type Person struct {
	Conversations []Conversation `json:"conversations"`
	Email         string         `json:"email"`
	Id            string         `json:"id"`
	Initials      string         `json:"initials"`
	Latest        string         `json:"latest"`
	Name          string         `json:"name"`
	Since         string         `json:"since"`
	Slot          AccountSlot    `json:"slot"`
	Tags          []string       `json:"tags"`
	When          string         `json:"when"`
	WritesTo      string         `json:"writesTo"`
}

// PlacedTag defines model for PlacedTag.
type PlacedTag struct {
	Count int    `json:"count"`
	Id    string `json:"id"`
	Name  string `json:"name"`
}

// ReadingFeed defines model for ReadingFeed.
type ReadingFeed struct {
	Digest string  `json:"digest"`
	Issues []Issue `json:"issues"`
}

// RestoreResult defines model for RestoreResult.
type RestoreResult struct {
	Restored int `json:"restored"`
}

// Rule defines model for Rule.
type Rule struct {
	// AccountId Empty means every account
	AccountId  string          `json:"accountId"`
	Actions    []RuleAction    `json:"actions"`
	Conditions []RuleCondition `json:"conditions"`
	Id         string          `json:"id"`
	Matches    int             `json:"matches"`
	On         bool            `json:"on"`
	Then       string          `json:"then"`
	ThenColor  *TagColor       `json:"thenColor,omitempty"`
	ThenToken  string          `json:"thenToken"`
	When       string          `json:"when"`
	WhenTail   *string         `json:"whenTail,omitempty"`
	WhenToken  *string         `json:"whenToken,omitempty"`
}

// RuleAction defines model for RuleAction.
type RuleAction struct {
	Snooze *RuleActionSnooze `json:"snooze,omitempty"`

	// TagId The tag for a `tag` action
	TagId *string        `json:"tagId,omitempty"`
	Type  RuleActionType `json:"type"`
}

// RuleActionSnooze defines model for RuleAction.Snooze.
type RuleActionSnooze string

// RuleActionType defines model for RuleAction.Type.
type RuleActionType string

// RuleApplyResult defines model for RuleApplyResult.
type RuleApplyResult struct {
	Applied int `json:"applied"`
}

// RuleCondition defines model for RuleCondition.
type RuleCondition struct {
	Field RuleConditionField `json:"field"`

	// Value A case-insensitive substring, an account id, or "true"/"false"
	Value string `json:"value"`
}

// RuleConditionField defines model for RuleCondition.Field.
type RuleConditionField string

// RuleDryRunRequest defines model for RuleDryRunRequest.
type RuleDryRunRequest struct {
	AccountIds *[]string       `json:"accountIds,omitempty"`
	Conditions []RuleCondition `json:"conditions"`
}

// RuleDryRunResult defines model for RuleDryRunResult.
type RuleDryRunResult struct {
	Matched int `json:"matched"`

	// Sample Up to twenty matched messages, for the review screen
	Sample *[]MailSummary `json:"sample,omitempty"`
	Total  int            `json:"total"`
}

// RuleInput defines model for RuleInput.
type RuleInput struct {
	AccountId  *string         `json:"accountId,omitempty"`
	Actions    []RuleAction    `json:"actions"`
	Conditions []RuleCondition `json:"conditions"`
	Enabled    *bool           `json:"enabled,omitempty"`
}

// RuleToggle defines model for RuleToggle.
type RuleToggle struct {
	Enabled bool `json:"enabled"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	AccountId string `json:"accountId"`

	// Date The message's instant, RFC 3339 in UTC (see MailSummary).
	Date          time.Time `json:"date"`
	From          string    `json:"from"`
	HasAttachment *bool     `json:"hasAttachment,omitempty"`
	Id            string    `json:"id"`
	Preview       string    `json:"preview"`
	Semantic      *bool     `json:"semantic,omitempty"`
	Subject       string    `json:"subject"`
	Tag           *string   `json:"tag,omitempty"`
}

// SearchResults defines model for SearchResults.
type SearchResults struct {
	Hits       []SearchHit `json:"hits"`
	NextCursor *string     `json:"nextCursor,omitempty"`
	Query      string      `json:"query"`
	Total      int         `json:"total"`
}

// SnoozeRequest defines model for SnoozeRequest.
type SnoozeRequest struct {
	Preset SnoozeRequestPreset `json:"preset"`
}

// SnoozeRequestPreset defines model for SnoozeRequest.Preset.
type SnoozeRequestPreset string

// SyncState defines model for SyncState.
type SyncState string

// TagColor defines model for TagColor.
type TagColor string

// TagCreate defines model for TagCreate.
type TagCreate struct {
	Color *TagColor `json:"color,omitempty"`

	// Name At most 64 characters
	Name string `json:"name"`
}

// TagUpdate defines model for TagUpdate.
type TagUpdate struct {
	Color *TagColor `json:"color,omitempty"`
	Name  *string   `json:"name,omitempty"`
}

// TagsOverview defines model for TagsOverview.
type TagsOverview struct {
	ActiveRules int         `json:"activeRules"`
	Mine        []UserTag   `json:"mine"`
	Placed      []PlacedTag `json:"placed"`
}

// UserTag defines model for UserTag.
type UserTag struct {
	Color TagColor `json:"color"`
	Count int      `json:"count"`
	Id    string   `json:"id"`
	Name  string   `json:"name"`

	// Slug The ASCII slug fixed at creation; the tag's IMAP keyword is `$ivy-<slug>`
	Slug string `json:"slug"`
}

// Version defines model for Version.
type Version struct {
	Version string `json:"version"`
}

// MessageID defines model for MessageID.
type MessageID = string

// OutboxID defines model for OutboxID.
type OutboxID = string

// RuleID defines model for RuleID.
type RuleID = string

// NotFound defines model for NotFound.
type NotFound = Error

// ListInboxParams defines parameters for ListInbox.
type ListInboxParams struct {
	AccountId *string `form:"account_id,omitempty" json:"account_id,omitempty"`

	// Folder A folder role, or `snoozed` for the local hidden-until list. Snoozed and Reading mail is hidden from every other view.
	Folder *ListInboxParamsFolder `form:"folder,omitempty" json:"folder,omitempty"`

	// Tag Show only mail carrying this tag id
	Tag    *string `form:"tag,omitempty" json:"tag,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListInboxParamsFolder defines parameters for ListInbox.
type ListInboxParamsFolder string

// ListOutboxParams defines parameters for ListOutbox.
type ListOutboxParams struct {
	AccountId *string `form:"account_id,omitempty" json:"account_id,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q string `form:"q" json:"q"`

	// AccountId Restrict to one account; repeatable for the combined view.
	AccountId *[]string `form:"account_id,omitempty" json:"account_id,omitempty"`
	Limit     *int      `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *string   `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UpdateAccountProfileJSONRequestBody defines body for UpdateAccountProfile for application/json ContentType.
type UpdateAccountProfileJSONRequestBody = AccountProfile

// AskJSONRequestBody defines body for Ask for application/json ContentType.
type AskJSONRequestBody = AskRequest

// SnoozeMessageJSONRequestBody defines body for SnoozeMessage for application/json ContentType.
type SnoozeMessageJSONRequestBody = SnoozeRequest

// EnqueueOutboxJSONRequestBody defines body for EnqueueOutbox for application/json ContentType.
type EnqueueOutboxJSONRequestBody = OutboxAction

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = RuleInput

// DryRunRuleJSONRequestBody defines body for DryRunRule for application/json ContentType.
type DryRunRuleJSONRequestBody = RuleDryRunRequest

// SetRuleEnabledJSONRequestBody defines body for SetRuleEnabled for application/json ContentType.
type SetRuleEnabledJSONRequestBody = RuleToggle

// UpdateRuleJSONRequestBody defines body for UpdateRule for application/json ContentType.
type UpdateRuleJSONRequestBody = RuleInput

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = TagCreate

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = TagUpdate
